
-- =============================================
-- Add missing Conversations table (referenced by badges.ts)
-- =============================================
create table if not exists conversations (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  session_id text not null, -- grouping messages
  scenario_id text,
  started_at timestamp with time zone default timezone('utc'::text, now()),
  ended_at timestamp with time zone,
  status text default 'active'
);

-- Enable RLS
alter table conversations enable row level security;

-- Policies
create policy "User Own Conversations" on conversations for all using (auth.uid() = user_id);

-- =============================================
-- Add Unique Constraint to Vocabulary (implied by service logic)
-- =============================================
alter table vocabulary add constraint vocabulary_word_key unique (word);
