
-- =============================================
-- 1. Profiles & Core Auth (matches users_extended)
-- =============================================
create table users_extended (
  id uuid references auth.users not null primary key,
  display_name text,
  username text unique,
  avatar_url text,
  
  -- Gamification Core
  total_xp int not null default 0,
  level int not null default 1,
  
  -- Streak Tracking
  current_streak int not null default 0,
  longest_streak int not null default 0,
  last_activity_date date,
  streak_freeze_count int not null default 0,
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- =============================================
-- 2. Vocabulary & SRS
-- =============================================
create table vocabulary (
  id bigint generated by default as identity primary key,
  word text not null,
  meaning text not null,
  pronunciation text,
  example text,
  category text default 'general',
  difficulty text default 'Beginner', 
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table user_vocabulary (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  vocab_id bigint references vocabulary(id) not null,
  is_learned boolean default false,
  
  -- SRS
  next_review timestamp with time zone default timezone('utc'::text, now()),
  interval int default 0,
  easiness_factor float default 2.5,
  repetition_number int default 0,
  last_reviewed_at timestamp with time zone,
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  unique(user_id, vocab_id)
);

-- Note: 'vocabulary_words' table referenced in badges.ts seems to be a view or alias of user_vocabulary JOIN vocabulary
-- Let's create a view for easier querying if the code expects 'vocabulary_words'
create view vocabulary_words as
  select 
    uv.id, 
    uv.user_id, 
    v.word, 
    v.meaning, 
    v.pronunciation, 
    uv.is_learned as learned, -- map learned -> is_learned
    uv.created_at
  from user_vocabulary uv
  join vocabulary v on uv.vocab_id = v.id;


-- =============================================
-- 3. Stories
-- =============================================
create table stories (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  difficulty text not null,
  category text,
  questions jsonb, -- Array of Question objects
  image_url text,
  audio_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table user_story_progress (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  story_id bigint references stories(id) not null,
  completed boolean default false,
  best_score int default 0,
  last_read_at timestamp with time zone,
  unique(user_id, story_id)
);

create table story_vocabulary (
  id bigint generated by default as identity primary key,
  story_id bigint references stories(id) not null,
  word text not null,
  definition text not null,
  context text
);


-- =============================================
-- 4. Daily Activities & Streaks
-- =============================================
create table daily_activities (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  activity_date date not null,
  activity_count int default 1,
  xp_earned int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, activity_date)
);

create table streak_milestones (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  milestone_days int not null,
  achieved_at timestamp with time zone default timezone('utc'::text, now()),
  badge_awarded text, -- ID of badge
  xp_awarded int default 0,
  unique(user_id, milestone_days)
);

create table streak_freeze_history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  freeze_date date not null,
  used_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, freeze_date)
);


-- =============================================
-- 5. Badges
-- =============================================
create table badge_definitions (
  id text primary key, -- e.g., 'vocab_master_1'
  name text not null,
  description text not null,
  icon text not null, -- emoji or url
  category text not null, -- 'streak', 'vocabulary', etc.
  requirement_type text not null, -- 'streak_days', 'words_learned'
  requirement_value int not null,
  xp_reward int default 0,
  rarity text default 'common',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table user_badges (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  badge_id text references badge_definitions(id) not null,
  unlocked_at timestamp with time zone default timezone('utc'::text, now()),
  progress jsonb default '{}',
  unique(user_id, badge_id)
);


-- =============================================
-- 6. Learning Path
-- =============================================
create table learning_path_items (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  description text,
  type text not null, -- 'lesson', 'practice', 'quiz'
  status text default 'locked', -- 'locked', 'available', 'completed'
  order_index int not null,
  action_url text,
  completed_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table user_learning_goals (
  user_id uuid references auth.users not null primary key,
  primary_goal text,
  current_level text,
  weekly_target_minutes int default 60,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);


-- =============================================
-- 7. Social / Challenges
-- =============================================
create table daily_challenges (
  id bigint generated by default as identity primary key,
  date date unique not null,
  tasks jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table user_challenges (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  challenge_id bigint references daily_challenges(id) not null,
  is_fully_completed boolean default false,
  progress jsonb,
  updated_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, challenge_id)
);

create table friendships (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  friend_id uuid references auth.users not null,
  status text default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, friend_id)
);


-- =============================================
-- 8. RLS Policies (Simplified)
-- =============================================
alter table users_extended enable row level security;
alter table vocabulary enable row level security;
alter table user_vocabulary enable row level security;
alter table stories enable row level security;
alter table story_vocabulary enable row level security;
alter table user_story_progress enable row level security;
alter table daily_activities enable row level security;
alter table streak_milestones enable row level security;
alter table streak_freeze_history enable row level security;
alter table badge_definitions enable row level security;
alter table user_badges enable row level security;
alter table learning_path_items enable row level security;
alter table user_learning_goals enable row level security;
alter table daily_challenges enable row level security;
alter table user_challenges enable row level security;
alter table friendships enable row level security;

-- Public Read common tables
create policy "Public Read Vocabulary" on vocabulary for select using (true);
create policy "Public Read Stories" on stories for select using (true);
create policy "Public Read Story Vocab" on story_vocabulary for select using (true);
create policy "Public Read Badges" on badge_definitions for select using (true);
create policy "Public Read Challenges" on daily_challenges for select using (true);
create policy "Public Read Profiles" on users_extended for select using (true);

-- User Private Access
create policy "User Own Data" on users_extended for all using (auth.uid() = id);
create policy "User Own Vocab" on user_vocabulary for all using (auth.uid() = user_id);
create policy "User Own Story Progress" on user_story_progress for all using (auth.uid() = user_id);
create policy "User Own Activity" on daily_activities for all using (auth.uid() = user_id);
create policy "User Own Milestones" on streak_milestones for all using (auth.uid() = user_id);
create policy "User Own Freeze" on streak_freeze_history for all using (auth.uid() = user_id);
create policy "User Own Badges" on user_badges for all using (auth.uid() = user_id);
create policy "User Own Path" on learning_path_items for all using (auth.uid() = user_id);
create policy "User Own Goals" on user_learning_goals for all using (auth.uid() = user_id);
create policy "User Own Challenge Progress" on user_challenges for all using (auth.uid() = user_id);
create policy "User Friends" on friendships for all using (auth.uid() = user_id or auth.uid() = friend_id);


-- =============================================
-- 9. RPC Functions (Logic for frontend calls)
-- =============================================

-- check_and_award_badges
create or replace function check_and_award_badges(p_user_id uuid)
returns void as $$
declare
  v_badge record;
  v_count int;
  v_streak int;
begin
  -- Get user stats
  select current_streak into v_streak from users_extended where id = p_user_id;
  
  -- Loop through definitions
  for v_badge in select * from badge_definitions loop
    -- Check Requirement
    if v_badge.requirement_type = 'streak_days' and v_streak >= v_badge.requirement_value then
      -- Insert if not exists
      insert into user_badges(user_id, badge_id)
      values (p_user_id, v_badge.id)
      on conflict do nothing;
    end if;
    
    -- Add other checks (vocab, etc.) here as needed
  end loop;
end;
$$ language plpgsql security definer;


-- use_streak_freeze
create or replace function use_streak_freeze(p_user_id uuid, p_freeze_date date)
returns json as $$
declare
  v_freeze_count int;
begin
  -- Check availability
  select streak_freeze_count into v_freeze_count from users_extended where id = p_user_id;
  
  if v_freeze_count > 0 then
    -- Record usage
    insert into streak_freeze_history(user_id, freeze_date) values (p_user_id, p_freeze_date)
    on conflict do nothing;
    
    -- Decrement count
    update users_extended set streak_freeze_count = streak_freeze_count - 1 where id = p_user_id;
    
    return json_build_object('success', true, 'message', 'Streak freeze used!');
  else
    return json_build_object('success', false, 'message', 'No freezes available');
  end if;
end;
$$ language plpgsql security definer;


-- check_streak_milestone
create or replace function check_streak_milestone(p_user_id uuid, p_current_streak int)
returns void as $$
begin
  -- Simple check for standard milestones
  if p_current_streak >= 7 then
    insert into streak_milestones(user_id, milestone_days, xp_awarded) values (p_user_id, 7, 50) on conflict do nothing;
  end if;
  if p_current_streak >= 30 then
     insert into streak_milestones(user_id, milestone_days, xp_awarded) values (p_user_id, 30, 200) on conflict do nothing;
  end if;
  -- Add more as needed
end;
$$ language plpgsql security definer;
